#!/usr/bin/env python3
"""The fitness function.

Runs the candidate agent against a fixed opponent pool over a fixed seed set
and reports win rate plus diagnostics. This number is the only evidence that
counts for "did that change help".

    python arena/run.py                     # full run vs pool
    python arena/run.py --quick             # 3 seeds vs starter
    python arena/run.py --opponents starter random
    python arena/run.py --seeds 20 --json results.json
    python arena/run.py --compare v1-early-capital-discipline  # head-to-head

Seeds are fixed by default so runs are comparable. Do not change SEEDS
casually - if you do, every prior result in strategy-log.md is invalidated.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from arena.metrics import (  # noqa: E402
    episode_metrics, format_summary, differential_report, format_differential,
)

SEEDS = [
    11, 23, 37, 41, 59, 67, 73, 89, 97, 103, 113, 127,  # original 12
    # +36, raising the default to 48 - see docs/strategy-log.md "Empirically
    # re-deriving the acceptance bar". Generated by random.Random(20260807),
    # deduped against the original 12.
    35076, 348020, 807329, 980136, 379189, 468253, 60401, 328408, 452954,
    865618, 499262, 303281, 491651, 382195, 998487, 81236, 935042, 88571,
    996510, 635145, 964674, 929061, 59803, 563431, 241203, 717227, 702931,
    564425, 638423, 948091, 154341, 94953, 956778, 659543, 909170, 757581,
]
DEFAULT_OPPONENTS = [
    "starter", "random_seeded", "v2-capital-reserve-fix",
    # Distinct-strategy pool, added after the self-play-echo-chamber risk
    # flagged when the arena was designed became real (see
    # docs/ladder-observations.md and docs/meta-analysis.md): every prior
    # opponent above is our own lineage or a trivial baseline.
    "animal-heavy", "melon-rush", "market-dumper",
]


def _git_info():
    """(sha, dirty) of the working tree, best-effort. Every arena result must
    be attributable to an exact code state - see docs/strategy-log.md
    "Arena determinism and noise-floor audit"."""
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except Exception:
        sha = "unknown"
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip())
    except Exception:
        dirty = None
    return sha, dirty


def _snapshot_agent_dir():
    """Copy agent/ into an isolated temp dir and run every episode against
    that snapshot instead of the live working tree.

    Root cause of a phantom "v0 stalls" result in a prior session: arena
    subprocesses were reading agent/main.py off disk while it was being
    edited in the foreground of the same working tree. This makes that
    structurally impossible - once copied, nothing running this arena
    invocation can see a subsequent edit. Not cleaned up automatically: for
    a dirty working tree, this snapshot is the only exact record of the code
    that actually ran, so it stays on disk for later inspection.
    """
    snap_root = Path(tempfile.mkdtemp(prefix="kaggri_arena_"))
    shutil.copytree(ROOT / "agent", snap_root / "agent")
    return snap_root / "agent"


def _load_agent(spec, snapshot_agent_dir):
    """spec is 'starter'/'random'/'pass', a frozen pool name, or a path.

    Any path that resolves inside the live agent/ directory (this includes
    the default --candidate) is redirected into the isolated snapshot.
    """
    if spec in ("starter", "random", "pass"):
        return spec
    p = Path(spec).resolve()
    agent_dir = (ROOT / "agent").resolve()
    try:
        rel = p.relative_to(agent_dir)
        return str(snapshot_agent_dir / rel)
    except ValueError:
        pass
    if p.exists():
        return str(p)
    frozen = ROOT / "arena" / "opponents" / spec / "main.py"
    if frozen.exists():
        return str(frozen)
    raise SystemExit(f"unknown agent: {spec}")


def _play(args):
    candidate, opponent, seed, swap, episode_steps, snapshot_agent_dir = args
    from kaggle_environments import make

    a = _load_agent(candidate, snapshot_agent_dir)
    b = _load_agent(opponent, snapshot_agent_dir)
    order = [b, a] if swap else [a, b]
    me = 1 if swap else 0

    # kaggle_environments clears configuration["seed"] before agents see it
    # (verified empirically - see strategy-log), so opponents that need a
    # reproducible RNG (arena/opponents/random_seeded) read it from here.
    os.environ["KAGGRI_ARENA_SEED"] = str(seed)

    env = make("kaggriculture",
               configuration={"episodeSteps": episode_steps, "seed": seed},
               debug=False)
    t0 = time.time()
    env.run(order)
    elapsed = time.time() - t0

    steps = env.steps
    banks = [steps[-1][0]["observation"]["farms"][i]["money"] for i in (0, 1)]
    my_bank, opp_bank = banks[me], banks[1 - me]
    result = 1 if my_bank > opp_bank else (0.5 if my_bank == opp_bank else 0)

    statuses = [steps[-1][i].get("status") for i in (0, 1)]
    errored = statuses[me] not in ("DONE", "ACTIVE", "INACTIVE")

    m = episode_metrics(steps, me)
    m.update(seed=seed, opponent=opponent, swap=swap, result=result,
             opp_bank=opp_bank, wall_s=round(elapsed, 1), errored=errored)
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", default=str(ROOT / "agent" / "main.py"))
    ap.add_argument("--opponents", nargs="*", default=DEFAULT_OPPONENTS)
    ap.add_argument("--seeds", type=int, default=len(SEEDS))
    ap.add_argument("--steps", type=int, default=720)
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 1))
    ap.add_argument("--json", default=None)
    ap.add_argument("--compare", default=None, metavar="REFERENCE",
                     help="Head-to-head candidate vs REFERENCE across the full seed "
                          "set, both seats. Overrides --opponents. Prints a paired "
                          "bank-differential report (t-test + Wilcoxon) in place of "
                          "the normal pool run.")
    args = ap.parse_args()

    if args.compare:
        seeds, opponents = SEEDS[:args.seeds], [args.compare]
    elif args.quick:
        seeds, opponents = SEEDS[:3], ["starter"]
    else:
        seeds, opponents = SEEDS[:args.seeds], args.opponents

    sha, dirty = _git_info()
    snapshot_agent_dir = _snapshot_agent_dir()

    # play both seats of every pairing - seat 0 spawns advantageously
    jobs = [(args.candidate, opp, s, swap, args.steps, snapshot_agent_dir)
            for opp in opponents for s in seeds for swap in (False, True)]

    print(f"git:       {sha}{'  (DIRTY - uncommitted changes)' if dirty else ''}")
    print(f"snapshot:  {snapshot_agent_dir}")
    print(f"opponents: {', '.join(opponents)}")
    print(f"arena: {len(jobs)} episodes  "
          f"({len(seeds)} seeds x {len(opponents)} opponents x 2 seats)")

    rows = []
    with ProcessPoolExecutor(max_workers=args.workers) as ex:
        for i, m in enumerate(ex.map(_play, jobs), 1):
            rows.append(m)
            tag = "W" if m["result"] == 1 else ("D" if m["result"] == 0.5 else "L")
            print(f"  [{i:>3}/{len(jobs)}] {tag} vs {m['opponent']:<10} "
                  f"seed={m['seed']:<4} bank={m['final_bank']:>9.0f} "
                  f"opp={m['opp_bank']:>9.0f} ({m['wall_s']}s)"
                  + ("  ERRORED" if m["errored"] else ""))

    print()
    errs = sum(1 for r in rows if r["errored"])
    if errs:
        print(f"!! {errs} episodes errored - fix before trusting anything below")

    diff_reports = {}
    for opp in opponents:
        sub = [r for r in rows if r["opponent"] == opp]
        wr = 100 * sum(r["result"] for r in sub) / len(sub)
        print(f"vs {opp:<12} win rate {wr:>6.1f}%  (ladder metric - win/loss only)   "
              f"mean bank {sum(r['final_bank'] for r in sub)/len(sub):>10.0f}")
        diffs = [r["final_bank"] - r["opp_bank"] for r in sub]
        report = differential_report(diffs)
        diff_reports[opp] = report
        print(format_differential(report, label=f"  vs {opp} bank diff (dev signal)"))

    overall = 100 * sum(r["result"] for r in rows) / len(rows)
    print(f"\nOVERALL WIN RATE  {overall:.1f}%   ({len(rows)} episodes)\n")
    print(format_summary(rows))

    if args.json:
        payload = {
            "meta": {
                "git_sha": sha,
                "git_dirty": dirty,
                "snapshot_agent_dir": str(snapshot_agent_dir),
                "candidate": args.candidate,
                "opponents": opponents,
                "seeds": seeds,
                "steps": args.steps,
            },
            "episodes": rows,
            "differential_reports": diff_reports,
        }
        Path(args.json).write_text(json.dumps(payload, indent=2, default=str))
        print(f"\nwrote {args.json}")

    return 0 if not errs else 1


if __name__ == "__main__":
    sys.exit(main())
